// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:13338/api/v1/' | (string & {});
};

export type PostAuthLoginData = {
    body: {
        username: string;
        password: string;
    };
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type PostAuthLoginErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Invalid username or password / You are already authenticated
     */
    401: {
        success: false;
        code: 401;
        message: 'Invalid username or password / You are already authenticated';
    };
    /**
     * Too many login attempts. Try again later.
     */
    429: {
        success: false;
        code: 429;
        message: 'Too many login attempts. Try again later.';
    };
};

export type PostAuthLoginError = PostAuthLoginErrors[keyof PostAuthLoginErrors];

export type PostAuthLoginResponses = {
    /**
     * Login successful
     */
    200: {
        success: true;
        code: 200;
        message: 'Login successful';
        data: {
            user_id: number;
            user_role: 'admin' | 'developer' | 'user';
            created_at: number;
            expires_at: number;
            token: string;
        };
    };
};

export type PostAuthLoginResponse = PostAuthLoginResponses[keyof PostAuthLoginResponses];

export type GetAuthSessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/session';
};

export type GetAuthSessionErrors = {
    /**
     * Unauthorized: Invalid or missing session token / Your Auth Context is not a session
     */
    401: {
        success: false;
        code: 401;
        message: 'Unauthorized: Invalid or missing session token / Your Auth Context is not a session';
    };
};

export type GetAuthSessionError = GetAuthSessionErrors[keyof GetAuthSessionErrors];

export type GetAuthSessionResponses = {
    /**
     * Session info retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Session info retrieved successfully';
        data: {
            user_id: number;
            user_role: 'admin' | 'developer' | 'user';
            created_at: number;
            expires_at: number;
        };
    };
};

export type GetAuthSessionResponse = GetAuthSessionResponses[keyof GetAuthSessionResponses];

export type PostAuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type PostAuthLogoutErrors = {
    /**
     * Unauthorized: Invalid or missing session token / Your Auth Context is not a session
     */
    401: {
        success: false;
        code: 401;
        message: 'Unauthorized: Invalid or missing session token / Your Auth Context is not a session';
    };
};

export type PostAuthLogoutError = PostAuthLogoutErrors[keyof PostAuthLogoutErrors];

export type PostAuthLogoutResponses = {
    /**
     * Logout successful
     */
    200: {
        success: true;
        code: 200;
        message: 'Logout successful';
        data: null;
    };
};

export type PostAuthLogoutResponse = PostAuthLogoutResponses[keyof PostAuthLogoutResponses];

export type PostAuthResetPasswordData = {
    body: {
        reset_token: string;
        /**
         * New password for the account
         */
        new_password: string;
    };
    path?: never;
    query?: never;
    url: '/auth/reset-password';
};

export type PostAuthResetPasswordErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * You are already authenticated
     */
    401: {
        success: false;
        code: 401;
        message: 'You are already authenticated';
    };
    /**
     * User for reset token not found
     */
    500: {
        success: false;
        code: 500;
        message: 'User for reset token not found';
    };
};

export type PostAuthResetPasswordError = PostAuthResetPasswordErrors[keyof PostAuthResetPasswordErrors];

export type PostAuthResetPasswordResponses = {
    /**
     * Password has been reset successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Password has been reset successfully';
        data: null;
    };
};

export type PostAuthResetPasswordResponse = PostAuthResetPasswordResponses[keyof PostAuthResetPasswordResponses];

export type PostAuthResetPasswordRequestData = {
    body: {
        email: string;
    };
    path?: never;
    query?: never;
    url: '/auth/reset-password/request';
};

export type PostAuthResetPasswordRequestErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * You are already authenticated
     */
    401: {
        success: false;
        code: 401;
        message: 'You are already authenticated';
    };
};

export type PostAuthResetPasswordRequestError = PostAuthResetPasswordRequestErrors[keyof PostAuthResetPasswordRequestErrors];

export type PostAuthResetPasswordRequestResponses = {
    /**
     * If the username exists, a password reset has been requested
     */
    200: {
        success: true;
        code: 200;
        message: 'If the username exists, a password reset has been requested';
        data: null;
    };
};

export type PostAuthResetPasswordRequestResponse = PostAuthResetPasswordRequestResponses[keyof PostAuthResetPasswordRequestResponses];

export type DeleteAccountData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/account';
};

export type DeleteAccountErrors = {
    /**
     * Your Auth Context is not a session
     */
    401: {
        success: false;
        code: 401;
        message: 'Your Auth Context is not a session';
    };
};

export type DeleteAccountError = DeleteAccountErrors[keyof DeleteAccountErrors];

export type DeleteAccountResponses = {
    /**
     * Account deleted successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Account deleted successfully';
        data: null;
    };
};

export type DeleteAccountResponse = DeleteAccountResponses[keyof DeleteAccountResponses];

export type GetAccountData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/account';
};

export type GetAccountErrors = {
    /**
     * Your Auth Context is not a session
     */
    401: {
        success: false;
        code: 401;
        message: 'Your Auth Context is not a session';
    };
};

export type GetAccountError = GetAccountErrors[keyof GetAccountErrors];

export type GetAccountResponses = {
    /**
     * Account information retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Account information retrieved successfully';
        data: {
            id: number;
            username: string;
            display_name: string;
            email: string;
            role: 'admin' | 'developer' | 'user';
            created_at: number;
        };
    };
};

export type GetAccountResponse = GetAccountResponses[keyof GetAccountResponses];

export type PutAccountData = {
    body: {
        username?: string;
        display_name?: string;
        email?: string;
    } & {
        /**
         * Current password — required to confirm account changes
         */
        current_password: string;
    };
    path?: never;
    query?: never;
    url: '/account';
};

export type PutAccountErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Your Auth Context is not a session
     */
    401: {
        success: false;
        code: 401;
        message: 'Your Auth Context is not a session';
    };
};

export type PutAccountError = PutAccountErrors[keyof PutAccountErrors];

export type PutAccountResponses = {
    /**
     * Account information updated successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Account information updated successfully';
        data: null;
    };
};

export type PutAccountResponse = PutAccountResponses[keyof PutAccountResponses];

export type PutAccountPasswordData = {
    body: {
        /**
         * Current password of the account
         */
        current_password: string;
        /**
         * New password for the account
         */
        new_password: string;
    };
    path?: never;
    query?: never;
    url: '/account/password';
};

export type PutAccountPasswordErrors = {
    /**
     * Current password is incorrect / Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Current password is incorrect / Syntax or validation error in request';
    };
    /**
     * Your Auth Context is not a session
     */
    401: {
        success: false;
        code: 401;
        message: 'Your Auth Context is not a session';
    };
};

export type PutAccountPasswordError = PutAccountPasswordErrors[keyof PutAccountPasswordErrors];

export type PutAccountPasswordResponses = {
    /**
     * Password changed successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Password changed successfully';
        data: null;
    };
};

export type PutAccountPasswordResponse = PutAccountPasswordResponses[keyof PutAccountPasswordResponses];

export type GetAdminUsersData = {
    body?: never;
    path?: never;
    query?: {
        role?: 'admin' | 'developer' | 'user';
        search?: string;
        limit?: number;
        offset?: number;
    };
    url: '/admin/users';
};

export type GetAdminUsersResponses = {
    /**
     * Users retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Users retrieved successfully';
        data: Array<{
            id: number;
            username: string;
            display_name: string;
            email: string;
            role: 'admin' | 'developer' | 'user';
            created_at: number;
        }>;
    };
};

export type GetAdminUsersResponse = GetAdminUsersResponses[keyof GetAdminUsersResponses];

export type PostAdminUsersData = {
    body: {
        username: string;
        display_name: string;
        email: string;
        role?: 'admin' | 'developer' | 'user';
        password: string;
    };
    path?: never;
    query?: never;
    url: '/admin/users';
};

export type PostAdminUsersErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Conflict: Username or email already exists
     */
    409: {
        success: false;
        code: 409;
        message: 'Conflict: Username or email already exists';
    };
};

export type PostAdminUsersError = PostAdminUsersErrors[keyof PostAdminUsersErrors];

export type PostAdminUsersResponses = {
    /**
     * User created successfully
     */
    201: {
        success: true;
        code: 201;
        message: 'User created successfully';
        data: {
            id: number;
            username: string;
            display_name: string;
            email: string;
            role: 'admin' | 'developer' | 'user';
            created_at: number;
        };
    };
};

export type PostAdminUsersResponse = PostAdminUsersResponses[keyof PostAdminUsersResponses];

export type DeleteAdminUsersByUserIdData = {
    body?: never;
    path: {
        userId: number;
    };
    query?: never;
    url: '/admin/users/{userId}';
};

export type DeleteAdminUsersByUserIdErrors = {
    /**
     * Cannot delete user while they own publishers
     */
    400: {
        success: false;
        code: 400;
        message: 'Cannot delete user while they own publishers';
    };
    /**
     * User not found
     */
    404: {
        success: false;
        code: 404;
        message: 'User not found';
    };
};

export type DeleteAdminUsersByUserIdError = DeleteAdminUsersByUserIdErrors[keyof DeleteAdminUsersByUserIdErrors];

export type DeleteAdminUsersByUserIdResponses = {
    /**
     * User deleted successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'User deleted successfully';
        data: null;
    };
};

export type DeleteAdminUsersByUserIdResponse = DeleteAdminUsersByUserIdResponses[keyof DeleteAdminUsersByUserIdResponses];

export type GetAdminUsersByUserIdData = {
    body?: never;
    path: {
        userId: number;
    };
    query?: never;
    url: '/admin/users/{userId}';
};

export type GetAdminUsersByUserIdErrors = {
    /**
     * User not found
     */
    404: {
        success: false;
        code: 404;
        message: 'User not found';
    };
};

export type GetAdminUsersByUserIdError = GetAdminUsersByUserIdErrors[keyof GetAdminUsersByUserIdErrors];

export type GetAdminUsersByUserIdResponses = {
    /**
     * User retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'User retrieved successfully';
        data: {
            id: number;
            username: string;
            display_name: string;
            email: string;
            role: 'admin' | 'developer' | 'user';
            created_at: number;
        };
    };
};

export type GetAdminUsersByUserIdResponse = GetAdminUsersByUserIdResponses[keyof GetAdminUsersByUserIdResponses];

export type PutAdminUsersByUserIdData = {
    body: {
        username?: string;
        display_name?: string;
        email?: string;
        role?: 'admin' | 'developer' | 'user';
    };
    path: {
        userId: number;
    };
    query?: never;
    url: '/admin/users/{userId}';
};

export type PutAdminUsersByUserIdErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * User not found
     */
    404: {
        success: false;
        code: 404;
        message: 'User not found';
    };
    /**
     * Conflict: Username or email already exists
     */
    409: {
        success: false;
        code: 409;
        message: 'Conflict: Username or email already exists';
    };
};

export type PutAdminUsersByUserIdError = PutAdminUsersByUserIdErrors[keyof PutAdminUsersByUserIdErrors];

export type PutAdminUsersByUserIdResponses = {
    /**
     * User updated successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'User updated successfully';
        data: {
            id: number;
            username: string;
            display_name: string;
            email: string;
            role: 'admin' | 'developer' | 'user';
            created_at: number;
        };
    };
};

export type PutAdminUsersByUserIdResponse = PutAdminUsersByUserIdResponses[keyof PutAdminUsersByUserIdResponses];

export type PutAdminUsersByUserIdPasswordData = {
    body: {
        /**
         * New password for the account
         */
        password: string;
    };
    path: {
        userId: number;
    };
    query?: never;
    url: '/admin/users/{userId}/password';
};

export type PutAdminUsersByUserIdPasswordErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * User not found
     */
    404: {
        success: false;
        code: 404;
        message: 'User not found';
    };
};

export type PutAdminUsersByUserIdPasswordError = PutAdminUsersByUserIdPasswordErrors[keyof PutAdminUsersByUserIdPasswordErrors];

export type PutAdminUsersByUserIdPasswordResponses = {
    /**
     * Password reset successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Password reset successfully';
        data: null;
    };
};

export type PutAdminUsersByUserIdPasswordResponse = PutAdminUsersByUserIdPasswordResponses[keyof PutAdminUsersByUserIdPasswordResponses];

export type GetClaudeProjectsData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        offset?: number;
        order?: 'newest' | 'oldest';
        searchString?: string;
    };
    url: '/claude/projects';
};

export type GetClaudeProjectsResponses = {
    /**
     * Projects retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Projects retrieved successfully';
        data: Array<{
            exists: true;
            name: string;
            absolute_path: string;
            last_used: number;
        }>;
    };
};

export type GetClaudeProjectsResponse = GetClaudeProjectsResponses[keyof GetClaudeProjectsResponses];

export type GetClaudeProjectsByAbsolutePathData = {
    body?: never;
    path: {
        /**
         * URI-encoded project absolute path
         */
        absolute_path: string;
    };
    query?: {
        /**
         * Whether to include sessions in the response
         */
        with_sessions?: boolean;
    };
    url: '/claude/projects/{absolute_path}';
};

export type GetClaudeProjectsByAbsolutePathResponses = {
    /**
     * Project retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Project retrieved successfully';
        data: {
            exists: true;
            name: string;
            absolute_path: string;
            last_used: number;
        } | {
            exists: false;
            name: string;
            absolute_path: string;
            last_used: unknown;
        } | {
            exists: true;
            name: string;
            absolute_path: string;
            last_used: number;
            sessions: Array<{
                session_id: string;
                title: string;
                last_modified: number;
                git_branch?: string;
                created_at?: number;
            }>;
        } | {
            exists: false;
            name: string;
            absolute_path: string;
            last_used: unknown;
            sessions: Array<{
                session_id: string;
                title: string;
                last_modified: number;
                git_branch?: string;
                created_at?: number;
            }>;
        };
    };
};

export type GetClaudeProjectsByAbsolutePathResponse = GetClaudeProjectsByAbsolutePathResponses[keyof GetClaudeProjectsByAbsolutePathResponses];

export type GetClaudeProjectsByAbsolutePathSessionsData = {
    body?: never;
    path: {
        /**
         * URI-encoded project absolute path
         */
        absolute_path: string;
    };
    query?: {
        limit?: number;
        offset?: number;
        order?: 'newest' | 'oldest';
        searchString?: string;
    };
    url: '/claude/projects/{absolute_path}/sessions';
};

export type GetClaudeProjectsByAbsolutePathSessionsResponses = {
    /**
     * Sessions retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Sessions retrieved successfully';
        data: Array<{
            session_id: string;
            title: string;
            last_modified: number;
            git_branch?: string;
            created_at?: number;
        }>;
    };
};

export type GetClaudeProjectsByAbsolutePathSessionsResponse = GetClaudeProjectsByAbsolutePathSessionsResponses[keyof GetClaudeProjectsByAbsolutePathSessionsResponses];

export type DeleteClaudeProjectsByAbsolutePathSessionsBySessionIdData = {
    body?: never;
    path: {
        /**
         * URI-encoded project absolute path
         */
        absolute_path: string;
        session_id: string;
    };
    query?: never;
    url: '/claude/projects/{absolute_path}/sessions/{session_id}';
};

export type DeleteClaudeProjectsByAbsolutePathSessionsBySessionIdErrors = {
    /**
     * Session not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Session not found';
    };
};

export type DeleteClaudeProjectsByAbsolutePathSessionsBySessionIdError = DeleteClaudeProjectsByAbsolutePathSessionsBySessionIdErrors[keyof DeleteClaudeProjectsByAbsolutePathSessionsBySessionIdErrors];

export type DeleteClaudeProjectsByAbsolutePathSessionsBySessionIdResponses = {
    /**
     * Session deleted successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Session deleted successfully';
        data: null;
    };
};

export type DeleteClaudeProjectsByAbsolutePathSessionsBySessionIdResponse = DeleteClaudeProjectsByAbsolutePathSessionsBySessionIdResponses[keyof DeleteClaudeProjectsByAbsolutePathSessionsBySessionIdResponses];

export type GetClaudeProjectsByAbsolutePathSessionsBySessionIdData = {
    body?: never;
    path: {
        /**
         * URI-encoded project absolute path
         */
        absolute_path: string;
        session_id: string;
    };
    query?: never;
    url: '/claude/projects/{absolute_path}/sessions/{session_id}';
};

export type GetClaudeProjectsByAbsolutePathSessionsBySessionIdErrors = {
    /**
     * Session not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Session not found';
    };
};

export type GetClaudeProjectsByAbsolutePathSessionsBySessionIdError = GetClaudeProjectsByAbsolutePathSessionsBySessionIdErrors[keyof GetClaudeProjectsByAbsolutePathSessionsBySessionIdErrors];

export type GetClaudeProjectsByAbsolutePathSessionsBySessionIdResponses = {
    /**
     * Session retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Session retrieved successfully';
        data: {
            session_id: string;
            title: string;
            last_modified: number;
            git_branch?: string;
            created_at?: number;
        };
    };
};

export type GetClaudeProjectsByAbsolutePathSessionsBySessionIdResponse = GetClaudeProjectsByAbsolutePathSessionsBySessionIdResponses[keyof GetClaudeProjectsByAbsolutePathSessionsBySessionIdResponses];

export type PutClaudeProjectsByAbsolutePathSessionsBySessionIdData = {
    body: {
        title: string;
    };
    path: {
        /**
         * URI-encoded project absolute path
         */
        absolute_path: string;
        session_id: string;
    };
    query?: never;
    url: '/claude/projects/{absolute_path}/sessions/{session_id}';
};

export type PutClaudeProjectsByAbsolutePathSessionsBySessionIdErrors = {
    /**
     * Session not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Session not found';
    };
};

export type PutClaudeProjectsByAbsolutePathSessionsBySessionIdError = PutClaudeProjectsByAbsolutePathSessionsBySessionIdErrors[keyof PutClaudeProjectsByAbsolutePathSessionsBySessionIdErrors];

export type PutClaudeProjectsByAbsolutePathSessionsBySessionIdResponses = {
    /**
     * Session renamed successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Session renamed successfully';
        data: {
            session_id: string;
            title: string;
            last_modified: number;
            git_branch?: string;
            created_at?: number;
        };
    };
};

export type PutClaudeProjectsByAbsolutePathSessionsBySessionIdResponse = PutClaudeProjectsByAbsolutePathSessionsBySessionIdResponses[keyof PutClaudeProjectsByAbsolutePathSessionsBySessionIdResponses];

export type GetClaudeProjectsByAbsolutePathSessionsBySessionIdMessagesData = {
    body?: never;
    path: {
        /**
         * URI-encoded project absolute path
         */
        absolute_path: string;
        session_id: string;
    };
    query?: never;
    url: '/claude/projects/{absolute_path}/sessions/{session_id}/messages';
};

export type GetClaudeProjectsByAbsolutePathSessionsBySessionIdMessagesErrors = {
    /**
     * Session not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Session not found';
    };
};

export type GetClaudeProjectsByAbsolutePathSessionsBySessionIdMessagesError = GetClaudeProjectsByAbsolutePathSessionsBySessionIdMessagesErrors[keyof GetClaudeProjectsByAbsolutePathSessionsBySessionIdMessagesErrors];

export type GetClaudeProjectsByAbsolutePathSessionsBySessionIdMessagesResponses = {
    /**
     * Session messages retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Session messages retrieved successfully';
        data: Array<{
            type: 'user' | 'assistant' | 'system';
            uuid: string;
            session_id: string;
            message: {
                role: 'user' | 'assistant';
                content: string | Array<{
                    type: 'text';
                    text: string;
                } | {
                    type: 'image';
                    source: {
                        type: 'base64' | 'url';
                        media_type: 'image/jpeg' | 'image/png' | 'image/gif' | 'image/webp';
                        data?: string;
                        url?: string;
                    };
                } | {
                    type: 'tool_use';
                    id: string;
                    name: string;
                    input: {
                        [key: string]: string | number | boolean | Array<{
                            [key: string]: string | number | boolean;
                        }>;
                    };
                } | {
                    type: 'tool_result';
                    tool_use_id: string;
                    content?: string | Array<{
                        type: 'text';
                        text: string;
                    }>;
                    is_error?: boolean;
                } | {
                    type: 'thinking';
                    thinking: string;
                    signature?: string;
                } | {
                    type: 'redacted_thinking';
                    data: string;
                }>;
            } | {
                id: string;
                type: 'message';
                role: 'assistant';
                content: Array<{
                    type: 'text';
                    text: string;
                } | {
                    type: 'thinking';
                    thinking: string;
                    signature: string;
                } | {
                    type: 'redacted_thinking';
                    data: string;
                } | {
                    type: 'tool_use';
                    id: string;
                    name: string;
                    input: {
                        [key: string]: string | number | boolean | Array<{
                            [key: string]: string | number | boolean;
                        }>;
                    };
                }>;
                model: string;
                stop_reason: string | null;
                stop_sequence: string | null;
                usage: {
                    input_tokens: number;
                    cache_creation_input_tokens: number | null;
                    cache_read_input_tokens: number | null;
                    output_tokens: number;
                    server_tool_use?: {
                        web_search_requests: number;
                        web_fetch_requests: number;
                    } | null;
                    service_tier: 'standard' | 'priority' | 'batch' | null;
                    cache_creation?: {
                        ephemeral_1h_input_tokens: number;
                        ephemeral_5m_input_tokens: number;
                    } | null;
                    inference_geo?: string | null;
                    iterations?: Array<{
                        type: 'message';
                        input_tokens: number;
                        output_tokens: number;
                        cache_creation_input_tokens: number;
                        cache_read_input_tokens: number;
                        cache_creation: {
                            ephemeral_1h_input_tokens: number;
                            ephemeral_5m_input_tokens: number;
                        } | null;
                        model: string;
                    } | {
                        type: 'compaction';
                        input_tokens: number;
                        output_tokens: number;
                        cache_creation_input_tokens: number;
                        cache_read_input_tokens: number;
                        cache_creation: {
                            ephemeral_1h_input_tokens: number;
                            ephemeral_5m_input_tokens: number;
                        } | null;
                    } | {
                        type: 'advisor_message';
                        input_tokens: number;
                        output_tokens: number;
                        cache_creation_input_tokens: number;
                        cache_read_input_tokens: number;
                        cache_creation: {
                            ephemeral_1h_input_tokens: number;
                            ephemeral_5m_input_tokens: number;
                        } | null;
                        model: string;
                    } | {
                        type: 'fallback_message';
                        input_tokens: number;
                        output_tokens: number;
                        cache_creation_input_tokens: number;
                        cache_read_input_tokens: number;
                        cache_creation: {
                            ephemeral_1h_input_tokens: number;
                            ephemeral_5m_input_tokens: number;
                        } | null;
                        model: string;
                    }> | null;
                    output_tokens_details?: {
                        text_tokens?: number;
                        thinking_tokens?: number;
                    } | null;
                    speed?: 'standard' | 'fast' | null;
                };
                stop_details?: {
                    type: 'early';
                } | null;
            } | {
                [key: string]: string | number | boolean | Array<{
                    [key: string]: string | number | boolean;
                }>;
            };
            parent_tool_use_id: string | null;
            timestamp?: string;
        }>;
    };
};

export type GetClaudeProjectsByAbsolutePathSessionsBySessionIdMessagesResponse = GetClaudeProjectsByAbsolutePathSessionsBySessionIdMessagesResponses[keyof GetClaudeProjectsByAbsolutePathSessionsBySessionIdMessagesResponses];
